### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by niconoe** [trias-project/risk-maps#10]
@peterdesmet : at a later stage, will you be available to make the web app looks better?

It will stay pretty small, and the toolbox is the same than Crow.

**Comment by peterdesmet** [comment]
Yes, let me know when you think it is necessary.

**Comment by peterdesmet** [comment]
Note to self: 1) add footer and 2) consider layout where all controls are on the side. Screenshot based on moving things in Chrome Developer Tools:

![trias_risk_map](https://user-images.githubusercontent.com/600993/87056525-0f451780-c206-11ea-9777-c21e931df626.png)

**Comment by niconoe** [comment]
Hey @peterdesmet (one year later already 😳)

I just updated the maps again. Since the app is apparently used and no new features were requested recently, I was wondering if we should finally style the page, issue a proper release and finally mention it on our webpage? What do you think?

**Comment by SoVDH** [comment]
Hi Nico and Peter, 
I feel that the site as it stands should not be 'officially released' at the moment. I would still like to keep it for internal use as the maps need to be included in risk assessment context or with accompanying information that is not ready at this stage for users. That's just my personal feeling ...

**Comment by niconoe** [comment]
Thanks @SoVDH!

Indeed, I understand the concern. To me, it was more about the tool itself (like being able to tell on our page "we have build a map viewer used for the TriAS project") than the use you are doing of it (we should stay internal - not publicly announced as long as you wish).

Those are/were two different things in my mind. But I'm not sure anymore, and don't want to add confusion to the situation. 
Maybe it would also be good to add a disclaimer "for internal use only, visit XXX if you want more info about invasives" at the top of the page, then?

Any other opinion on this?

**Comment by SoVDH** [comment]
Let's see what the others think about this. I'm not the only ones. ;-)

**Comment by amyjsdavis** [comment]
I did not see the problem in releasing it as a map viewer for the TrIAS project. It is a part of the risk assessment process, not the full procedure. However, I defer to @SoVDH, who can certainly better anticipate the problems of doing this better than I. :-)

**Comment by peterdesmet** [comment]
I would release it with a disclaimer. @amyjsdavis @SoVDH can you provide a short sentence that we can display at the top of the application. Something along the lines below:

> The maps and models shown below are in an experimental state and should not be used for policy ...

**Comment by peterdesmet** [comment]
Before:

![b0cdf29f-2283-4b29-b4c5-c92f1054b021](https://user-images.githubusercontent.com/600993/111792380-7bfbd000-88c4-11eb-9caf-093c735181ae.png)

After:

![5fb6d190-3569-45ed-996b-34c2a8383dc4](https://user-images.githubusercontent.com/600993/111794592-ae0e3180-88c6-11eb-80a0-387eaab95310.png)
