### ISSUE TITLE
Start with a default

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/risk-maps#13]
I think would be nice if the application started with a loaded example, e.g. the first value from each dropdown (excluding "Ecoregions"), rather than:

<img width="303" alt="Screenshot 2020-04-03 at 13 42 08" src="https://user-images.githubusercontent.com/600993/78356999-ee3eac00-75b0-11ea-8c1f-1c0ac6241e90.png">

**Comment by niconoe** [comment]
Yeah, will do!
