### ISSUE TITLE
Select all elements of overlay element of one type

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/risk-maps#15]
When selecting an area, all areas of that type should be highlighted, so it is clear that these are of the same type. E.g. three areas for polder, while currently only one is highlighted:

<img width="403" alt="Screenshot 2020-04-03 at 13 58 18" src="https://user-images.githubusercontent.com/600993/78358322-4aa2cb00-75b3-11ea-8702-b499fd3b2292.png">

**Comment by peterdesmet** [comment]
Note: when clicking an element, the zoom should also bound all three elements, rather than one.

**Comment by timadriaens** [comment]
you could simply do that on the shapefile itself in arcgis, with the merge polygon function
