### ISSUE TITLE
Correct names of biogeographic districts (ecoregions) + missing ones

### ISSUE THREAD

**Issue by SoVDH** [trias-project/risk-maps#17]
I don't know where you got them from, but the names of biogeographic districts (ecoregions) are not complete in Wallonia and do not refer to what is commonly used as far as I know. 
- Condroz
- Fagne-Famenne-Calestienne
- Thiérache
- Ardenne
- Gaume et Lorraine

Also, Maybe worth having both FR and NL names for the users? 

<img width="1280" alt="Capture d’écran 2020-04-07 à 10 54 34" src="https://user-images.githubusercontent.com/16779819/78650284-01a68b80-78bf-11ea-810c-b6f5a9073c93.png">
<img width="1280" alt="Capture d’écran 2020-04-07 à 10 59 24" src="https://user-images.githubusercontent.com/16779819/78650294-04a17c00-78bf-11ea-8b49-612bd1b2d131.png">

**Comment by niconoe** [comment]
No problem for me, it's always a messy process to get/assemble/hack the right file for such things (if you have good ones in a GIS format, please send it to me!). Is the one from your second screenshot correct? Then I can ask Julien for the file. No problem for the three languages, I'll just need someone to give me a table with the names in each languages.

**Comment by timadriaens** [comment]
English names [here](https://github.com/trias-project/risk-modelling-and-mapping/issues/5)

**Comment by SoVDH** [comment]
@niconoe  Perfectly fine with both English names and delineation.
