### ISSUE TITLE
Background layer

### ISSUE THREAD

**Issue by SoVDH** [trias-project/risk-maps#19]
I'm not a big fan of the background layer. What is available? It is mainly cities and rivers that are interesting. Not really roads in my opinion.

**Comment by niconoe** [comment]
Thanks, I'll look for alternatives. We might be limited if we don't setup our own map server (we'd like to avoid that) or use a paid service such as Mapbox. We might be able to hack something by combining a very light background with a river overlay, for example. I'll be back to you for this!

**Comment by niconoe** [comment]
More work is probably needed, but as a first step I changed the background layer style to [HOT OSM](https://www.hotosm.org/). It's visually lighter and gives a bit more visibility to green areas and water.

**Comment by peterdesmet** [comment]
Nice!

**Comment by SoVDH** [comment]
@niconoe Nickel! It is a nice balance between cities and natural characteristics :) Merci !
