### ISSUE TITLE
Add Atlantic vs Continental

### ISSUE THREAD

**Issue by SoVDH** [trias-project/risk-maps#20]
Would it be possible to add as overlay the simple 'atlantic' vs 'continental domain' ? These are basic unit used for risk analysis and users will need them anyway.

**Comment by niconoe** [comment]
Is this a simple layer with two polygons (Atlantic and Continental)? If so:

- Do you know where I can find such a file (in a GIS-compatible format)?
- Would the logic described by Peter in #16 also works for this layer?

**Comment by SoVDH** [comment]
- I have to ask colleagues at DEMNA. Maybe INBO also has these kind of shape file as it is required for N2000 reporting.

- Yes, the same logic can apply here.

**Comment by niconoe** [comment]
Hey @timadriaens: do you have a shapefile at hand with the those "Atlantic" vs "Continental" domains?

**Comment by timadriaens** [comment]
on our gis server (which you can access through the citrix workspace), under S:\Europa\Natuur_Bos\BiogeoRegions. I uploaded a clip on github for Belgium of the 2016 layer we used for the manageability maps.

**Comment by niconoe** [comment]
Done!
