### ISSUE TITLE
Map overlaps with control on smaller screens

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/risk-maps#22]
This hides the controls on smaller screens:

<img width="1011" alt="Screenshot 2020-06-08 at 13 03 56" src="https://user-images.githubusercontent.com/600993/84023594-a8bfa600-a988-11ea-8654-04836a1f8528.png">

**Comment by niconoe** [comment]
Thanks. Note to self: possible solution: https://codepen.io/tforward/pen/ZPeZxd
