### ISSUE TITLE
how to show occurrences on risk maps

### ISSUE THREAD

**Issue by amyjsdavis** [trias-project/risk-maps#24]
Hi All: I am sorry I missed this last month. I had asked Nico (while I was unaware of this thread) to only show only the occurrence data I used to make the risk models,  because there is sometimes a big difference between the date I used and the occurrences that are shown in the risk mapping application. Now that I've read through this thread, it seems like the biggest differences in the occurrence data he is showing and the one I used for the risk modelling is time and excluding data based on coordinate uncertainty. In order to align the models with the historic climate data, only data from 1976 to 2005 are used in my models. I had prepared shapefiles that show the occurrence data used in the models for Belgium and that is  ideally what I like to use since he can't filter based on coordinate uncertainty. The 2nd best option is to filter the data based on time. I think that would make the occurrence data closely approximate what was used in the risk models. What do you all think? @niconoe   

_Originally posted by @amyjsdavis in https://github.com/trias-project/risk-maps/issues/21#issuecomment-652449558_

**Comment by damianooldoni** [comment]
Hi @amyjsdavis , I gave you right now access to this repository with "maintain" rights as for all of us members of the TrIAS Core group. So from now on you can reopen issues, mention people and many other stuff. 

I close this issue as I reopened the other one.
