### ISSUE TITLE
missing maps

### ISSUE THREAD

**Issue by amyjsdavis** [trias-project/risk-maps#28]
@niconoe: @SoVDH noticed that maps for 5281901 (Campylopus introflexus) are not showing on the viewer.  The geoTIFFS for this species are in the google drive folder you created for GeoTIFFs, but they are in  a subfolder I created for my last upload called PRA_Plants_noUnverified. (This upload addresses the issue of unverified occurrences that @damianooldoni discovered last summer). This folder contains the final maps that should be used in the viewer, including the one for Campylopus. 

I realize now that I created confusion by adding subfolders, and if you like, I will clean up the google drive folder leaving only the final version of the maps only while eliminating duplicates and subfolders. I wanted to check with you first. Thanks!

**Comment by DiederikStrubbe** [comment]
Thanks Amy!

Diederik

Op do 21 jan. 2021 5:33 p.m. schreef Amy JS Davis <notifications@github.com

**Comment by niconoe** [comment]
Thanks for the report Amy!

Indeed, I think the cleanest solution is to just keep a single (root) folder, with all the maps that should be in the viewer, and only the maps that should be in the viewer. So, no duplicates and no subfolders. Is this okay for you? Don't hesitate to ping me once it's done and I'll quickly update the map viewer.

**Comment by amyjsdavis** [comment]
@niconoe : apologies for the delay (I did not realize you had replied!). This works for me!  I will let you know when it's done. It should be later today.

**Comment by amyjsdavis** [comment]
@niconoe : everything is now in the root folder. I've also added new risk maps. Thanks for your help!

**Comment by niconoe** [comment]
@amyjsdavis @DiederikStrubbe @SoVDH:

I updated the app so it's in currently in sync with the root GeoTiff folder. Please test and report any issue!
