### ISSUE TITLE
Show git revision on page (in footer?)

### ISSUE THREAD

**Issue by niconoe** [trias-project/risk-maps#33]
That's always useful for traceability reasons (or just to check if a deployment was successful)

**Comment by peterdesmet** [comment]
Yes please, if you give me the code I can incorporate it. Or should I just copy paste from CROW?

**Comment by peterdesmet** [comment]
Nico, the boilerplate code is here:

https://github.com/trias-project/risk-maps/blob/a6839755eed18e6d5459fe25342a864aba75b76b/src/App.vue#L17-L20
