### ISSUE TITLE
Add disclaimer

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/risk-maps#35]
I would release it with a disclaimer. @amyjsdavis @SoVDH can you provide a short sentence that we can display at the top of the application. Something along the lines below:

> The maps and models shown below are in an experimental state and should not be used for policy ...

_Originally posted by @peterdesmet in https://github.com/trias-project/risk-maps/issues/10#issuecomment-802809047_

**Comment by peterdesmet** [comment]
Note to self once I have the sentence, insert here and remove `d-none`:

https://github.com/trias-project/risk-maps/blob/a6839755eed18e6d5459fe25342a864aba75b76b/src/components/Home.vue#L3-L5

**Comment by amyjsdavis** [comment]
@SoVDH : what about stating something like: " This map viewer currently only communicates one part of the risk assessment process and should not be used for policy making"

**Comment by timadriaens** [comment]
imo there should be a little more than a disclaimer if the maps are released beyond the people that risk assess. It should at least be explained somewehere what the 3 model types represent (with an info button perhaps?). "Modelled data" is also something that is not readily clear to everyone, as is "historical climate data". Also, if these maps "should not be used for policy making" then why did we make them right... I think there is no problem for them to be used, so long as people know their worth and limitations.

**Comment by peterdesmet** [comment]
Text by @qgroom:

> Invasive alien species have the potential to damage ecosystems, reduce biodiversity and cause other problems for people and wildlife. In order to mitigate these problems research is needed into what the potential risks are and which species are most likely to be a problem. One of the techniques we use is species distribution modelling. These models aim to estimate the potential distribution of a species given the known environmental conditions where it is currently living. In such models we can also incorporate future scenarios into such models, so that we can account for climate change in our evaluation of risk.
> 
> These maps are unlikely to be precise predictions of current or future species distributions, but are nevertheless a guide to scientists conducting risk assessments. They help us by indicating which areas might be most vulnerable to invasion, and whether climate change is likely to cause greater or lesser spread of the species.
