### ISSUE TITLE
overlay rivers and/or river basins

### ISSUE THREAD

**Issue by timadriaens** [trias-project/risk-maps#36]
for the sake of having some more information on riparian and aquatic IAS, I think it would be nice to have some overlay maps regarding the hydrographical network. Rivers and canals people can see if they zoom in, but being able to put the river basins in Belgium on the risk map would be very informative. Ijzer, Schelde, Maas and Rein are of course very big delineations, it would be nice to have something a bit more detailed e.g. at the level of river basin management planning.

the least we can do is perhaps to provide the [river basin units](https://www.eea.europa.eu/data-and-maps/data/wise-river-basin-districts-rbds-1) used by the Water Framework Directive but perhaps the subunits are more informative since they are more the level used for river management planning (and IAS management should be at that level).

**Comment by peterdesmet** [comment]
If these data are available, @niconoe should be able to add these. @timadriaens which file should we use: https://www.eea.europa.eu/data-and-maps/data/wise-wfd-spatial-3

**Comment by timadriaens** [comment]
the 2016 one

**Comment by timadriaens** [comment]
Although this layer is already something, it is of course very 'low resolution' (Schelde, Maas, Rein). In fact, we would need a little bit more detail to make them really useful for end-users. Something that corresponds to the main river basins. What we would need is the following maps:

- [ ] [Vlaamse Hydrografische Atlas: VHA-bekkens](http://www.geopunt.be/catalogus/datasetfolder/07ed9e60-214f-461b-ad26-4642392e03d2) for Flanders
- [ ] for Wallonia a map like HydroWal.shp on the INBO GIS server which has the river basins (ourthe, amblève etc.), which could be [this one](http://geoportail.wallonie.be/catalogue/25d56977-de06-4504-9e35-ca28447c3a45.html) unless @niconoe knows where to find a better one

I can't seem to find a map with those basins for Belgium online and inspire proof so looks like we would have to stitch.

**Comment by niconoe** [comment]
Thanks for the request, @timadriaens!

I had a quick look and already have some questions:

- In terms of user interface, is it okay if it uses the same system/logic than the current overlays (ecoregions/bioregions): only one overlay at once, zone name appear on mouse hover, ...?
- Should the two files above (Flanders/Wallonia) be aggregated and appear within the same overlay?
- For the Flanders file, I noticed it contains actually 3 different *.shp files. Could you tell me which one we should use?
- About Walloon data: I requested the data (had to explain the use, give my coordinates, ...). Open Data is not there yet, hope they'll agree and the conditions will allow us to actually use them :/

**Comment by timadriaens** [comment]
great! Some responses:

- yes the same logic is perfectly fine, just an overlay cf. the bioregions, zones appearing on mouse hover
- the two files should indeed be aggregated unless we can find a layer of the belgian "bassins versants" somewhere (but I was unable to find one on the various EU, Belgian and regional geoportals)
- For Flanders, the level we need is the `bekken.shp` (and the column "BEKNAAM" is what we need for the mouse hover)
- Good. Times they are changing :-)

**Comment by niconoe** [comment]
Cool! In the meantime I received the walloon data in my mailbox, I'll merge those and update the viewer soon!

**Comment by niconoe** [comment]
@timadriaens: that's now implemented, can you have a look?

**Comment by timadriaens** [comment]
Looking good!

**Comment by timadriaens** [comment]
One small comment perhaps @niconoe "drainage basins" is a less used term over here, I would simply go for "river basins"

**Comment by niconoe** [comment]
Good to know, I'll update that!
