### ISSUE TITLE
Occurrence maps for species without risk modelling

### ISSUE THREAD

**Issue by niconoe** [trias-project/risk-maps#38]
Request from May 6th meeting:

- Show more species, not only the ones we have GeoTiff for.
- Occurrence data would still originates in the same data cube (=show all occurrences from the cube)
- Occurrences would be filtered: only show 1976-2020 
- Need a user-friendly way to announce to users which species has risk maps or not

**Comment by niconoe** [comment]
(should it be on this map or not - still in discussion)

**Comment by peterdesmet** [comment]
Decided to:

- Indeed expand the list to all species in the cube (= all species of the unified checklist that have occurrences in Belgium).
- Allow user to limit list to those species that have models. I suggest a checkbox
- Allow user to limit list based on kingdom. That aspect will be added in the next cube: https://github.com/trias-project/occ-cube-alien/issues/32. I suggest an additional dropdown before the species dropdown.

To be decided:

- Maybe be can have the "modelled species" as an option in the "kingdom" dropdown, as a single way to limit the species list, but I'm not sure if that is going to scale well.
- Should we still show the modelled map by default?

**Comment by niconoe** [comment]
I've now implemented this feature. Can you have a look at https://trias-project.github.io/risk-maps/ and give me feedback? Thanks!

**Comment by peterdesmet** [comment]
That looks cool! I like the emoji use. However, it seems that all taxa have 🌍 ? If so, I would remove that icon and only indicate if there is modelled data, which will improve readability.

**Comment by niconoe** [comment]
Indeed, all taxa currently have occurrences. 

I've build the system to be a bit more flexible than that and allows any modelled/occurrence data combination. That's why the user interface currently reflects that. But I agree about your usability concern, I'll fix that!

**Comment by niconoe** [comment]
Done!

@SoVDH , @timadriaens , @qgroom : does that work for you?

**Comment by SoVDH** [comment]
Waw, Super cool ! Thanks a lot @niconoe :-)
