### ISSUE TITLE
Make sure the system is reusable/can be embedded in Julien's future developments

### ISSUE THREAD

**Issue by niconoe** [trias-project/risk-maps#5]
@silenius: here is in a nutshell the envisioned development. Since the idea is that this work is at a later step embedded in a larger development you'll made for TriAS, I wanted to make sure the approach I take suits you. The plan at this stage is:

- A simple (if possible frontend-only) app that display the content of GeoTiff files over a Leaflet map of Belgium. There will be some usual overlays (ecoregions, N2000 zones, ...)
- Implemented using Vue.JS/TypeScript (Vue-CLI for a single page application - the written vue components can obviously be reused in other contexts-
- The app and UI would be pretty basic: a `select` to choose a given species, another `select` to choose a "map type" (there are multiple geotiffs generated per-species, for example to show the species progression according to various climate scenarii). From those two selects, we can infer a filename for the GeoTiff, and bam => on map.
- I'll use some frontend framework (probably Bootstrap, except if you have other suggestions/preferences) to have a basic page structure and nice form. It'll be limited, so it should be relatively easy to remove/replace them if needed when you do further integration.

Don't hesitate to comment!

**Comment by silenius** [comment]
Hi @niconoe: hard to say as at this stage I have no clear view on what should be done for TriAS from my side, especially the interaction with the protocols and how it all fits. I would say that if I can import a Vue component in the future webapp it should be OK ..

**Comment by niconoe** [comment]
Cool, that was my understanding too. Obviously there are many uncertainties and the "reuse code as it was lego parts" is often a bit naïve, but at least we have the less worst approach :)
