### ISSUE TITLE
Collect existing GeoTiffs

### ISSUE THREAD

**Issue by niconoe** [trias-project/risk-maps#7]

**Comment by niconoe** [comment]
@amyjsdavis: could you already send me the files that are ready? Do you have any preferred exchange medium? II admit 'm not sure of the current data volume, we'll figure out a solution.

**Comment by amyjsdavis** [comment]
@niconoe: Hi Nico: I realized the filies are still in the "wonky" projection.I am fixing the code now.  Is ETRS  89 ok or would you rather have WGS 84 (lat/lon)?  

As for the exchange medium, I can probably give you the first 10 files associated with 1 species over Github, but we probably need to figure something else out. I don't have any brilliant ideas other than dropBox or google drive. Suggestions welcome!

**Comment by niconoe** [comment]
Hey,

You can let them in ETRS89, I'll convert them as needed (I suppose it's more confortable for you, and I'll made the process automatic, so it won't be tedious for me).

Google drive / Dropbox seems good for this, I'll create a folder somewhere and send you the link by e-mail!

**Comment by niconoe** [comment]
You should now have received a Google Drive invitation to a folder!

**Comment by amyjsdavis** [comment]
Ok! perfect! Let me know if you change your mind about ETRS 89.

**Comment by niconoe** [comment]
We now have the process/shared drive in place.
